version: '3.8'

services:
  etcd:
    image: bitnami/etcd:latest
    container_name: citus-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - citus-network

  coordinator:
    build: .
    container_name: citus-coordinator
    environment:
      - POSTGRES_DB=citus
      - POSTGRES_USER=citus
      - POSTGRES_PASSWORD=citus123
      - PATRONI_NAME=coordinator
      - PATRONI_SCOPE=citus
      - PATRONI_ETCD_HOSTS=etcd:2379
    ports:
      - "5432:5432"
    volumes:
      - coordinator_data:/var/lib/postgresql/data
      - ./patroni.yml:/etc/patroni.yml:ro
      - ./sql:/docker-entrypoint-initdb.d:ro
    depends_on:
      - etcd
    networks:
      - citus-network

  worker1:
    build: .
    container_name: citus-worker1
    environment:
      - POSTGRES_DB=citus
      - POSTGRES_USER=citus
      - POSTGRES_PASSWORD=citus123
      - PATRONI_NAME=worker1
      - PATRONI_SCOPE=citus
      - PATRONI_ETCD_HOSTS=etcd:2379
    ports:
      - "5433:5432"
    volumes:
      - worker1_data:/var/lib/postgresql/data
      - ./patroni.yml:/etc/patroni.yml:ro
    depends_on:
      - etcd
    networks:
      - citus-network

  worker2:
    build: .
    container_name: citus-worker2
    environment:
      - POSTGRES_DB=citus
      - POSTGRES_USER=citus
      - POSTGRES_PASSWORD=citus123
      - PATRONI_NAME=worker2
      - PATRONI_SCOPE=citus
      - PATRONI_ETCD_HOSTS=etcd:2379
    ports:
      - "5434:5432"
    volumes:
      - worker2_data:/var/lib/postgresql/data
      - ./patroni.yml:/etc/patroni.yml:ro
    depends_on:
      - etcd
    networks:
      - citus-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: citus-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@citus.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8080:80"
    depends_on:
      - coordinator
    networks:
      - citus-network

volumes:
  coordinator_data:
  worker1_data:
  worker2_data:

networks:
  citus-network:
    driver: bridge
